name: 'Publish docs'
description: 'Publishes docs to github pages'
inputs:
  from:
    description: The location of the docs
    required: true
  publish-to:
    description: "The folder in the branch to put the docs in.  See README.md."
    required: false
  latests:
    description: "The values to replace $latest with in publish-to.  Snapshot, then release, separated by a '|'."
    required: false
    default: 'snapshot|release"
  branch:
    description: The branch to push docs to
    required: false
    default: 'gh-pages'
  version:
    description: "The version of the documentation.  Used if publish-to is 'version' or 'version+latest'"
    required: false
  message:
    description: "Message for the docs commit"
    required: false
  restore:
    description: Whether to restore the cwd after pushing
    required: false
    default: 'true'
  author-name:
    description: The name of the user that will be displayed as the author of the commit
    required: false
    default: ${{ github.actor }}
  author-email:
    description: The email of the user that will be displayed as the author of the commit
    required: false
    default: ${{ github.actor }}@users.noreply.github.com
runs:
  using: 'node12'
  main: 'dist/index.js'